---
repos:
  # General file formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Python formatting and linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
      - id: ruff-format
        name: ruff format

  # Type checking with MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-redis
          - types-requests
          - pydantic
          - pydantic-settings
        args: [--strict, --show-error-codes, --ignore-missing-imports]
        files: ^src/

  # Security scanning with Bandit
  - repo: local
    hooks:
      - id: bandit-src
        name: bandit security scan
        entry: uv run bandit -r src/ --skip B101
        language: system
        files: ^src/.*\.py$
        pass_filenames: false
      - id: safety-check
        name: safety vulnerability scan
        entry: uv run safety scan --output json --short-report
        language: system
        pass_filenames: false

  # YAML, JSON, and TOML validation
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]

default_language_version:
  python: python3.13

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto-format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆️ [pre-commit.ci] Pre-commit hook autoupdate
