---
name: Local Testing with act

on:
  workflow_dispatch:
  push:

jobs:
  basic-test:
    name: Basic Local Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Python version
        run: |
          python3 --version
          which python3

      - name: Check directory structure
        run: |
          pwd
          ls -la

      - name: Install uv manually
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify uv installation
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv --version

      - name: Create basic test directory
        run: |
          mkdir -p test-results
          echo "Basic test completed at $(date)" > test-results/basic-test.txt

      - name: Show test results
        run: |
          cat test-results/basic-test.txt
          ls -la test-results/

  simple-code-quality:
    name: Simple Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Check code formatting (basic)
        run: |
          echo "Checking basic formatting..."
          # Basic syntax check if Python files exist
          if find . -name "*.py" -type f | head -1 > /dev/null; then
            echo "Found Python files, checking syntax..."
            # Very basic syntax check
            python3 -m py_compile $(find . -name "*.py" -type f | head -5) || echo "Some syntax issues found"
          else
            echo "No Python files found in current directory"
          fi

      - name: Check for common issues
        run: |
          echo "Checking for common configuration files..."
          ls -la | grep -E '\.(yml|yaml|toml|json|md)$' || echo "No config files found"

          echo "Checking directory structure..."
          find . -maxdepth 2 -type d | head -10
